version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dio
      MONGO_INITDB_ROOT_PASSWORD: dio

  mongo-express:
    image: mongo-express
    ports:
      - "8080:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dio
      ME_CONFIG_MONGODB_ADMINPASSWORD: dio
      ME_CONFIG_MONGODB_URL: mongodb://dio:dio@mongo:27017/

  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - mongo-express
